BookReadingEvents/Controllers/AdminController.cs
using BookReadingEvents.BusinessLogic;
using BookReadingEvents.Domain;
using BookReadingEvents.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BookReadingEvents.Controllers
{
    public class AdminController : Controller
    {
        private readonly EventBusinessLogic eventBusinessLogic;
        private readonly UserBusinessLogic userBusinessLogic;

        public AdminController() {
            eventBusinessLogic = new EventBusinessLogic();
            userBusinessLogic = new UserBusinessLogic();
        }

        public ActionResult Index()
        {
            var events = eventBusinessLogic.GetAll();
            List<AdminViewModel> model = new List<AdminViewModel>();

            foreach (var evnt in events) {
                AdminViewModel viewModel = new AdminViewModel
                {
                    Event = evnt,
                    User = userBusinessLogic.GetUserById(evnt.UserId)
                };
                model.Add(viewModel);
            }

            return View(model);
        }

        public ActionResult FutureEvents() {
           
            var events = eventBusinessLogic.GetAllUpcomingEvents();
            List<AdminViewModel> model = new List<AdminViewModel>();

            foreach (var evnt in events)
            {
                AdminViewModel viewModel = new AdminViewModel
                {
                    Event = evnt,
                    User = userBusinessLogic.GetUserById(evnt.UserId)
                };
                model.Add(viewModel);
            }

            return View(model);

        }

        public ActionResult PastEvents() {
            var events = eventBusinessLogic.GetAllPastEvents();
            List<AdminViewModel> model = new List<AdminViewModel>();

            foreach (var evnt in events)
            {
                AdminViewModel viewModel = new AdminViewModel
                {
                    Event = evnt,
                    User = userBusinessLogic.GetUserById(evnt.UserId)
                };
                model.Add(viewModel);
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(Guid eventId) {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Event newEvent) {
            eventBusinessLogic.UpdateEvent(newEvent);
            return RedirectToAction("Index");
        }

        public ActionResult Details(Guid eventId) {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(Guid eventId) {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(Event myEvent) {
            eventBusinessLogic.DeleteEvent(myEvent.EventId);
            return RedirectToAction("Index");
        }
    
    }



}

BookReadingEvents/Controllers/LoginController.cs
using BookReadingEvents.BusinessLogic;
using BookReadingEvents.DataAccess.Services;
using BookReadingEvents.Domain;
using BookReadingEvents.Domain.Enums;
using BookReadingEvents.ViewModels;
using System;
using System.Web.Mvc;

namespace BookReadingEvents.Controllers
{
    public class LoginController : Controller
    {
      
        private readonly UserBusinessLogic userData;
        private readonly EventBusinessLogic eventData;
       
        public LoginController() {

            userData = new UserBusinessLogic();
            eventData = new EventBusinessLogic();
          
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginViewModel viewModel)
        {
            User user = new User
            {
                Email = viewModel.Email,
                Password = viewModel.Password 

            };

            if (ModelState.IsValid)
            {
                int loginFlag = userData.LoginVerifications(user);

                if (loginFlag == 0)
                {
                    user = userData.GetUserByEmail(user.Email);
                    Session["Email"] = user.Email;
                    Session["Id"] = user.UserId;
                    return RedirectToAction("Index", "Events");
                }
                else if (loginFlag == 1)
                {
                    user = userData.GetUserByEmail(user.Email);
                    Session["Email"] = user.Email;
                    Session["Id"] = user.UserId;
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    ViewBag.Message = "The user does not exist!";
                    return View();
                }
            }
            else {
                return View();
            }
         
           
        }

        [HttpGet]
        public ActionResult SignUp() {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(User viewModel) {

            User user = new User
            {
                Email = viewModel.Email,
                Password = viewModel.Password
            };

            if (ModelState.IsValid)
            {
                int canUserBeAdded = userData.SignUpVerifications(user);

                if (canUserBeAdded == -1)
                {
                    ViewBag.Message = "Error!! A user with same email already exists!";
                    //same email
                    return View();
                }
                else if (canUserBeAdded == 0)
                {
                 
                        userData.AddUser(user);
                        user = userData.GetUserByEmail(user.Email);
                        Session["Email"] = user.Email;
                        Session["Id"] = user.UserId;
                        return RedirectToAction("Index", "Events");
                   


                }
                else
                {
                        userData.AddUser(user);
                        user = userData.GetUserByEmail(user.Email);
                        Session["Email"] = user.Email;
                        Session["Id"] = user.UserId;
                        return RedirectToAction("Index", "Admin");
                   
                }
            }
            else
            {
                return View();
            }
          
            }
        

        [HttpGet]
        public ActionResult AllEventsBeforeLoginSignup()
        {
            var model = eventData.GetAllPublicEvents();
            return View(model);
        }

        public ActionResult RenderEventsPartialView() {
            return PartialView("_EventsBeforeLoginSignupPartialView");
        }
        
        [HttpGet]
        public ActionResult Details(Guid eventId) {
            Event myEvent = eventData.GetEventByEventId(eventId);
            return View(myEvent);
        }
    
    }
}

BookReadingEvents/Controllers/TableDataController.cs
using BookReadingEvents.BusinessLogic;
using BookReadingEvents.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookReadingEvents.Controllers
{
    public class TableDataController : Controller
    {
        private readonly EventBusinessLogic eventBusinessLogic;
        private readonly InvitessBusinessLogic inviteesBusinessLogic;
        public TableDataController()
        {
            eventBusinessLogic = new EventBusinessLogic();
            inviteesBusinessLogic = new InvitessBusinessLogic();
        }

        public ActionResult Index() {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(Guid eventId) {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        public ActionResult Edit(Event newEvent) {
            eventBusinessLogic.UpdateEvent(newEvent);
            return RedirectToAction("MyEvents" , "Events"); 
        }
        
        public ActionResult Detail(Guid eventId)
        {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(Guid eventId)
        {
            var model = eventBusinessLogic.GetEventByEventId(eventId);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Guid eventId, FormCollection form)
        {
            inviteesBusinessLogic.DeleteInvitees(eventId);
            eventBusinessLogic.DeleteEvent(eventId);
            return RedirectToAction("MyEvents", "Events");
        }
    }
}

BookReadingEvents/Views/Shared/_EventsBeforeLoginSignupPartialView.cshtml
@model IEnumerable<BookReadingEvents.Domain.Event>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherDetails)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OtherDetails)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", "Login", new { eventId = item.EventId }, null)
            </td>
        </tr>
    }

</table>

BookReadingEvents/Views/Shared/_EventsPartialView.cshtml
@model IEnumerable<BookReadingEvents.Domain.Event>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OtherDetails)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OtherDetails)
            </td>
            <td>
                @Html.ActionLink("Details", "Detail", "TableData", new { eventId = item.EventId }, null)
            </td>
        </tr>
    }

</table>

BookReadingEvents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookReadingEvents", "Index", "Events", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Events", "MyEvents", "Events")</li>
                    <li>@Html.ActionLink("Invited To", "EventsInvitedTo", "Events")</li>
                </ul>
                <ul class="nav navbar-nav mr-auto">
                    <li>@Html.ActionLink("Logout", "Logout", "Events")</li>
                    <li><a href="https://http://helpdesk.nagarro.com/kayako/">Customer-Support</a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BookReadingEvents/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookReadingEvents Admin", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                     <li>@Html.ActionLink("Future Events", "FutureEvents","Admin")</li>
                    <li>@Html.ActionLink("Past Events" , "PastEvents" , "Admin")</li>
                </ul>
                <ul class="nav navbar-nav mr-auto">
                    <li>@Html.ActionLink("Logout", "Logout", "Events")</li>
                    <li><a href="https://http://helpdesk.nagarro.com/kayako/">Customer-Support</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BookReadingEvents/Views/Shared/_LayoutLoginSignup.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookReadingEvents", "AllEventsBeforeLoginSignup", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Index")</li>
                    <li>@Html.ActionLink("Sign Up", "SignUp")</li>
                    <li><a href="https://http://helpdesk.nagarro.com/kayako/">Customer-Support</a></li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>